DECLARE
  --∂®“ÂSQL DDL”Ôæ‰
  v_SQLStr VARCHAR(200):=' CREATE TABLE BOOKS(ID int NOT NULL,BOOKNAME varchar2(100) NULL) ';
BEGIN
  EXECUTE IMMEDIATE v_SQLStr;  --÷¥––DDL”Ôæ‰
END;

DROP TABLE BOOKS;