package com.test.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CounterService service = new CounterService();
 * CounterDelegate portType = service.get1989();
 * portType.add(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CounterService", targetNamespace = "http://webservice.test.com/", wsdlLocation = "http://localhost:8080/wsd/1989?wsdl")
public class CounterService extends Service {

	private final static URL COUNTERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.test.webservice.CounterService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.test.webservice.CounterService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:8080/wsd/1989?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/wsd/1989?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		COUNTERSERVICE_WSDL_LOCATION = url;
	}

	public CounterService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CounterService() {
		super(COUNTERSERVICE_WSDL_LOCATION, new QName(
				"http://webservice.test.com/", "CounterService"));
	}

	/**
	 * 
	 * @return returns CounterDelegate
	 */
	@WebEndpoint(name = "1989")
	public CounterDelegate get1989() {
		return super.getPort(new QName("http://webservice.test.com/", "1989"),
				CounterDelegate.class);
	}

}
