
CREATE TABLE EMAIL_LIST
(
  GROUP_ID          NUMBER,
  GROUP_NAME        VARCHAR2(64 BYTE),
  DESCRIPTION       VARCHAR2(240 BYTE),
  SUBJECT           VARCHAR2(4000 BYTE),
  MTO               VARCHAR2(4000 BYTE),
  MCC               VARCHAR2(4000 BYTE),
  MBCC              VARCHAR2(4000 BYTE),
  MESSAGE           VARCHAR2(4000 BYTE),
  EFFECTIVE_DATE    DATE,
  DISABLE_DATE      DATE,
  MSENDER           VARCHAR2(2000 BYTE),
  APPLICATION_ID    NUMBER,
  SCHEDULING        VARCHAR2(16 BYTE),
  SCH_TIMING        VARCHAR2(2400 BYTE),
  SCH_SCRIPT        VARCHAR2(4000 BYTE),
  SCH_JOB           NUMBER,
  CREATION_DATE     DATE,
  CREATED_BY        NUMBER,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER
)
TABLESPACE VTTPC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

